# Generated by Django 4.2.7 on 2024-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_is_staff_user_is_admin_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Voiture'), ('truck', 'Gros porteur')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
