# Generated by Django 4.2.7 on 2024-07-30 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_contact_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='client_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_contact', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
